language: python

python:
  - "3.3"
  - "3.4"

env:
  global:
    - PYTHONPATH=.:$PYTHONPATH
  matrix:
    - DJANGO=Django==1.7.10 OSCAR=django-oscar==1.0.2
    - DJANGO=Django==1.7.10 OSCAR=django-oscar==1.1.1
    - DJANGO=Django==1.8.4 OSCAR=django-oscar==1.1.1

install:
  - pip install $DJANGO $OSCAR
  - pip install -r requirements.txt

script: py.test tests
